language: node_js
node_js: node
services:
- mongodb
cache:
  directories:
    - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key: 2607907a-85a1-461e-85ab-3ef4fdaf22cd
  app: murmuring-caverns-85624
  on:
    repo: mntri4/react-inventory-ease-api