language: node_js
node_js: node
services:
- mongodb
cache:
  directories:
    - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key: f524b4dd-b47d-4ab0-9330-fbec19c0b94d
  app: morning-cliffs-23218
  on:
    repo: DrewBlake/react-inventory-ease-api